spring:
  application:
    name: "Black Swan User's Task"
  datasource:
    password: sa
    username: sa
    url: jdbc:h2:./db/sbDb;DB_CLOSE_DELAY=1
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:./db/sbDb;DB_CLOSE_DELAY=1
    password: sa
    user: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    include-exception: true
  servlet:
    context-path: "/api"